Issue 2 viewing the entries
dcatan89/code-journal pull request #6
Opened 2021-12-27 00:38 UTC by dcatan89

<img width="562" alt="Screen Shot 2021-12-26 at 4 29 23 PM" src="https://user-images.githubusercontent.com/90487207/147423773-45805765-dd10-4a0b-95ac-abee9c6b9c40.png">
<img width="1166" alt="Screen Shot 2021-12-26 at 4 35 37 PM" src="https://user-images.githubusercontent.com/90487207/147423775-6e3dad36-eb98-4f23-b4b5-b0224dd812d5.png">
<img width="1145" alt="Screen Shot 2021-12-26 at 4 35 56 PM" src="https://user-images.githubusercontent.com/90487207/147423776-7878e554-0007-40c6-90bf-a855673c01eb.png">
<img width="1132" alt="Screen Shot 2021-12-26 at 4 36 13 PM" src="https://user-images.githubusercontent.com/90487207/147423777-74768544-eca4-4aba-90fd-8bc836c79b20.png">

2021-12-27 22:43 UTC, dcatan89 commented
![issue2](https://user-images.githubusercontent.com/90487207/147511803-23d27f94-3bed-4386-b2d2-9ddfd2dacd79.gif)

2021-12-27 23:08 UTC, codingcodymiller requested changes

2021-12-27 23:08 UTC, codingcodymiller commented on js/main.js
> +  }
You can reduce all this to the following:
```
  for (var i = 0; i < $view.length; i++) {
    if ($view[i].getAttribute('data-view') === string) {
      $view[i].classList.remove('hidden');
    } else {
      $view[i].classList.add('hidden');
    }
  }
```

2021-12-27 23:08 UTC, codingcodymiller commented on js/main.js
> +  }
Examine this and make sure you understand how it works, please ask me any questions if you have them.

2021-12-27 23:08 UTC, codingcodymiller commented on js/main.js
> +  event.preventDefault();
this line is not necessary, you only need to prevent default behavior for submit event handlers.

2021-12-27 23:08 UTC, codingcodymiller commented on js/main.js
> +  }
All of this functionality is already covered in `dataView`. You should just call `dataView` with an argument of the value of the `data-view` attribute on the anchor element that was clicked

2021-12-27 23:08 UTC, codingcodymiller commented on js/main.js
> +  $ulEntries.prepend(generateEntriesDOMTree(entryValues));
Does the view change to the entries view when you submit the form? The app should go to the entries view as soon as the new entry is submitted.

2021-12-27 23:34 UTC, dcatan89 commented
![issue 2 2](https://user-images.githubusercontent.com/90487207/147513639-36eb0381-5ade-4dad-a8a4-fe59204ec163.gif)

2021-12-27 23:45 UTC, codingcodymiller requested changes

2021-12-27 23:45 UTC, codingcodymiller commented on js/main.js
> +  var $dataViewEntries = event.target.getAttribute('data-view');
Rename this to `viewName`

2021-12-27 23:45 UTC, codingcodymiller commented on js/main.js
> +  }
You can remove this, it's already in `dataView`

2021-12-27 23:45 UTC, codingcodymiller commented on js/main.js
> +function viewSwapEntries(event) {
Rename this to `handleViewSwap`

2021-12-27 23:45 UTC, codingcodymiller commented on js/main.js
> +  }
You can replace all this with `dataView(viewName)`. All this looping to check the view is already done in `dataView`.

2021-12-28 01:23 UTC, codingcodymiller requested changes

2021-12-28 01:23 UTC, codingcodymiller commented on js/main.js
> +  }
This still needs to be addressed

2021-12-28 01:26 UTC, codingcodymiller approved these changes

2021-12-28 01:26 UTC, merged